export enum EnvironmentVariableConstants {
  APPLICATION_CONTROLLERS = 'APPLICATION_CONTROLLERS',
  APPLICATION_PORT = 'APPLICATION_PORT',
  APPLICATION_ROUTE_PREFIX = 'APPLICATION_ROUTE_PREFIX',
  NODE_ENV = 'NODE_ENV'
}
