export enum EnvironmentVariables {
  APPLICATION_CONTROLLERS,
  APPLICATION_LOG_LEVEL,
  APPLICATION_MIDDLEWARES,
  APPLICATION_PORT,
  APPLICATION_ROUTE_PREFIX,
  // database
  DATABASE_ENTITIES,
  DATABASE_LOGGING,
  DATABASE_MIGRATIONS,
  DATABASE_SUBCRIBERS,
  DATABASE_SYNCHRONIZE,
  DATABASE_TYPE,
  DATABASE_URL,
  // running environment
  NODE_ENV
}
