export enum EnvironmentVariable {
  APPLICATION_CONTROLLERS,
  APPLICATION_LOGGER_TYPE,
  APPLICATION_LOG_LEVEL,
  APPLICATION_MIDDLEWARES,
  APPLICATION_PORT,
  APPLICATION_ROUTER_DIR,
  APPLICATION_ROUTE_PREFIX,
  NODE_ENV
}
