export const EnvironmentVariableConstants = {
  APPLICATION_CONTROLLERS: 'APPLICATION_CONTROLLERS',
  APPLICATION_PORT: 'APPLICATION_PORT',
  NODE_ENV: 'NODE_ENV',
  APPLICATION_ROUTE_PREFIX: 'APPLICATION_ROUTE_PREFIX'
};
