#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Linting before commiting"
echo

CHANGED_DIRS=$(git diff-index --name-only HEAD | grep -v '^\.' | cut -d/ -f1 | sort -u)

for DIRNAME in ${CHANGED_DIRS}; do
  echo "Started linting changes in ${DIRNAME}"
  cd $PWD/${DIRNAME} && npx lint-staged
  echo "Finished linting changes in ${DIRNAME}"
  echo
done
